### ISSUE TITLE
Platforms

### ISSUE THREAD

**Issue by jsmrcaga** [jsmrcaga/action-social-post#1]
Vote below (with emojis) with reactions for more platforms*:
- Facebook 👍 
- ~Slack~ _Added in v1.1.0_ 🎉 
- Telegram 🚀 
- Twitter 👀

For more please add a comment below
* have to check API if OAuth not required or tokens easily

**Comment by cerebrux** [comment]
Can I suggest IRC or am I being boomer :)

**Comment by jsmrcaga** [comment]
@cerebrux IRC can be cool, thinking of Twitch ?

**Comment by scottmathson** [comment]
How about publishing to Instagram? Perhaps with this package https://github.com/jlobos/instagram-web-api

**Comment by jsmrcaga** [comment]
@scottmathson hum, instagram is harder, the only official API is the business API as far as I'm aware. It might deserve a whole project to itself

**Comment by jsmrcaga** [comment]
I haven't had time to continue work here, closing the issue since it's 4 years old
